apiVersion: circlerr.io/v1alpha1
kind: Circle
metadata:
  name: dev
spec:
  segments:
    - key: email
      condition: "="
      value: mail@mail.com
  environments:
    - key: API
      value: http://service:8080
  release:
    name: release-charles-v2
    projects:
      - name: guestbook
        image: latest
  destination:
    namespace: default
