apiVersion: circlerr.io/v1alpha1
kind: Circle
metadata:
  name: qa
spec:
  segments:
    - key: email
      condition: "="
      value: mail1@mail.com
  environments:
    - key: API
      value: http://service:8080
  release:
    name: release-charles-v5
    projects:
      - name: nginx
        image: latest
  destination:
    namespace: default
